[package]
name = "onvif-rs"
version = "0.0.1"
description = "Onvif Client in rust"
authors = ["Mayank Asthana <mayankasthana1993@gmail.com>"]
license = "MIT"
keywords = ["camera", "onvif", "cctv"]


[lib]
name = "onvif"

[dependencies]
quick-xml = "0.12.0"

